### PR TITLE
Update to fontawesome 4.7.0

### PR DESCRIPTION
**Pull request by ewohnlich**
There are 41 new icons in fontawesome 4.7.0. It doesn't look like anything was modified, just new font/css added.

### CODE REVIEW

**Comment by mck9** [comment]
Would be great to see this merged...

**Comment by gbastien** [comment]
Hi @ewohnlich @mck9 

Indeed, could you please adapt CHANGES.txt and README.rst?

I will merge when done, thank you.

Gauthier

**Comment by mck9** [comment]
Lightspeed! thanks @ewohnlich @gbastien

**Comment by gbastien** [comment]
Hi @ewohnlich @mck9 

I released version 1.0.5 (https://pypi.python.org/pypi/collective.fontawesome/) and updated the @@example.collective.fontawesome to include what is new in version 4.7.0

Thank you and have a nice day,

Gauthier

**Pull request merged**
